import typescript from "@rollup/plugin-typescript";
import { nodeResolve } from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";
import css from "rollup-plugin-css-only";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/
`;

export default {
    input: "./src/publish/publish.admonition.ts",
    output: {
        file: "./publish/publish.admonition.js",
        sourcemap: "inline",
        sourcemapExcludeSources: true,
        format: "cjs",
        banner
    },
    plugins: [
        typescript(),
        nodeResolve({ browser: true }),
        commonjs(),
        css({ output: "publish.admonition.css" })
    ]
};
