const typescript = require ("@rollup/plugin-typescript");
const { nodeResolve } = require ("@rollup/plugin-node-resolve");
const commonjs = require("@rollup/plugin-commonjs");
const css = require ("rollup-plugin-css-only");

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/
`;

module.exports = {
    input: "./src/main.ts",
    output: {
        dir: ".",
        sourcemap: "inline",
        sourcemapExcludeSources: true,
        format: "cjs",
        exports: "default",
        banner
    },
    external: ["obsidian"],
    plugins: [
        typescript(),
        nodeResolve({ browser: true }),
        commonjs(),
        css({ output: "styles.css" })
    ]
};
