name: Documentation Report
description: Request Documentation Update
labels: documentation
title: "[Docu]: "
assignees: 
 - Sigrunixia
body:
  - type: checkboxes
    id: investigation
    attributes:
      label: "What are we changing or adding?"
      description: "Please pick where you are requesting the documentation to change."
      options:
        - label: "Repository"
          required: false
        - label: "[Publish Documentation](https://plugins.javalent.com/)"
          required: false


  - type: textarea
    id: location
    validations:
      required: true
    attributes:
      label: "Location"
      description: "In what section are we changing?"
      placeholder: "We're changing this in the pinned threads."

  - type: textarea
    id: issue
    validations:
      required: true
    attributes:
      label: "The issue is..."
      description: "Describe what is the reason and motivation for this change?"
      placeholder: "I do not understand this terminology that is being used here..."

  - type: textarea
    id: suggestions
    validations:
      required: true
    attributes:
      label: "Suggestions?"
      description: "Do you have any suggestions on what wording can be changed or added?"
      placeholder: "I have pondered and here is a small write-up ..."

  - type: textarea
    id: anything-else
    validations:
      required: true
    attributes:
      label: "Anything else?"
      description: "Did we miss anything? What else do you want to add?"
      placeholder: "I think the Settings Search song sucks, and the mascot should be Murder Gemmy."
