name: Feature Request
description: Request a new feature
labels: Feature
title: "[Feature]: "
assignees:
 - Valentine195
 - Sigrunixia
body:
  - type: checkboxes
    id: duplicate-issues
    attributes:
      label: "Please make sure this feature request hasn't been suggested before."
      description: "Before submitting a feature request, please check if it has already been suggested in our Discussions or Issues pages. Use the **Label filters** to refine your search."
      options:
        - label: "I searched previous Issues and didn't find any similar feature requests."
          required: true

  - type: textarea
    id: feature-description
    validations:
      required: true
    attributes:
      label: "Feature description"
      description: "Please provide a clear and concise description of the feature you are requesting."
      placeholder: "I would like to see ..."

  - type: textarea
    id: solution
    validations:
      required: true
    attributes:
      label: "Solution"
      description: "Please describe your proposed solution for this feature request, and explain why it's necessary."
      placeholder: "In my use case, it would be helpful to have ..."

  - type: textarea
    id: alternatives
    validations:
      required: true
    attributes:
      label: "Alternatives"
      description: "Please provide any alternative solutions or features you've considered. Be clear and concise."
      placeholder: "I have considered ..."

  - type: textarea
    id: additional-context
    validations:
      required: true
    attributes:
      label: "Additional Information"
      description: "If you have any additional context or screenshots related to your feature request, please add them here."
      placeholder: "..."
